In [ ]:
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix,accuracy_score
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
encoder=LabelEncoder()
df['species']=encoder.fit_transform(df['species'])

In [ ]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [ ]:
df=df[['sepal_length','petal_length','species']]

In [ ]:
df.head()

   sepal_length  petal_length  species
0           5.1           1.4        0
1           4.9           1.4        0
2           4.7           1.3        0
3           4.6           1.5        0
4           5.0           1.4        0

In [ ]:
X=df.iloc[:,:2]
y=df.iloc[:,-1]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
clf=LogisticRegression( solver='lbfgs')
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)

In [ ]:
# Softmax regression implemented from scratch
X_train_np = X_train.to_numpy(dtype=float)
X_test_np = X_test.to_numpy(dtype=float)
y_train_np = y_train.to_numpy(dtype=int)
y_test_np = y_test.to_numpy(dtype=int)

def add_bias_term(X):
    return np.c_[np.ones((X.shape[0], 1)), X]

def softmax(z):
    z = z - np.max(z, axis=1, keepdims=True)
    exp_z = np.exp(z)
    return exp_z / np.sum(exp_z, axis=1, keepdims=True)

def one_hot(y, num_classes):
    encoded = np.zeros((y.shape[0], num_classes))
    encoded[np.arange(y.shape[0]), y] = 1
    return encoded

def fit_softmax_regression(X, y, learning_rate=0.1, epochs=2000):
    X_bias = add_bias_term(X)
    num_samples, num_features = X_bias.shape
    num_classes = len(np.unique(y))
    weights = np.zeros((num_features, num_classes))
    y_one_hot = one_hot(y, num_classes)

    for _ in range(epochs):
        probabilities = softmax(X_bias @ weights)
        gradient = (X_bias.T @ (probabilities - y_one_hot)) / num_samples
        weights -= learning_rate * gradient

    return weights

def predict_softmax_regression(X, weights):
    X_bias = add_bias_term(X)
    return np.argmax(softmax(X_bias @ weights), axis=1)

weights = fit_softmax_regression(X_train_np, y_train_np, learning_rate=0.1, epochs=2000)
y_pred = predict_softmax_regression(X_test_np, weights)

print('Accuracy:', accuracy_score(y_test_np, y_pred))
print(classification_report(y_test_np, y_pred))
cm = confusion_matrix(y_test_np, y_pred)
print('Confusion Matrix:\n', cm)

plt.figure(figsize=(6,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=encoder.classes_, yticklabels=encoder.classes_)
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Softmax Regression Confusion Matrix')
plt.show()

1.0