# Feature construction:-feature splitting
Feature Splitting is the process of splitting a feature into multiple features. This is done to capture the underlying structure of the data and to improve the performance of the model.
For example, if we have a feature called "date of birth", we can split it
into three features: "day of birth", "month of birth", and "year of birth". This can help the model to capture the underlying structure of the data and to improve the performance of the model.

In [85]:
import numpy as np 
import pandas as pd 
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
import seaborn as sns

In [86]:
df=pd.read_csv('../../feature_engineering/discretization&binarization/train.csv')[['Age','Pclass','SibSp','Parch','Survived']]

In [87]:
df.head()

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [88]:
df.dropna(inplace=True)

In [89]:
df.head()

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [90]:
X=df.drop('Survived',axis=1)
y=df['Survived']

In [91]:
np.mean(cross_val_score(LogisticRegression(),X,y,cv=19))

np.float64(0.6979112076064984)

# Applying feature construction on the titanic dataset

In [92]:
X['Family_size']=X['SibSp']+X['Parch']+1

In [93]:
X.head()

    Age  Pclass  SibSp  Parch  Family_size
0  22.0       3      1      0            2
1  38.0       1      1      0            2
2  26.0       3      0      0            1
3  35.0       1      1      0            2
4  35.0       3      0      0            1

In [94]:
def myfunc(num):
    if num==1:
        return 0
    elif num>1 and num<=4:
        return 1
    else:
        return 2

In [95]:
X['Family_type']=X['Family_size'].apply(myfunc)

In [96]:
X.head()

    Age  Pclass  SibSp  Parch  Family_size  Family_type
0  22.0       3      1      0            2            1
1  38.0       1      1      0            2            1
2  26.0       3      0      0            1            0
3  35.0       1      1      0            2            1
4  35.0       3      0      0            1            0

In [97]:
X.drop(columns=['SibSp','Parch','Family_size'],inplace=True)

In [98]:
X.head()

    Age  Pclass  Family_type
0  22.0       3            1
1  38.0       1            1
2  26.0       3            0
3  35.0       1            1
4  35.0       3            0

In [99]:
np.mean(cross_val_score(LogisticRegression(),X,y,scoring='accuracy',cv=19))

np.float64(0.7021411993711163)

# feature splitting

In [100]:
dff=pd.read_csv('../../feature_engineering/discretization&binarization/train.csv')

In [101]:
dff['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [105]:
dff['Title']=dff['Name'].apply(lambda x: x.split(',')[1].split('.')[0].strip())

In [106]:
dff[['Name','Title']].head()

                                                Name Title
0                            Braund, Mr. Owen Harris    Mr
1  Cumings, Mrs. John Bradley (Florence Briggs Th...   Mrs
2                             Heikkinen, Miss. Laina  Miss
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)   Mrs
4                           Allen, Mr. William Henry    Mr

In [109]:
(dff.groupby('Title')['Survived'].mean()*100).sort_values(ascending=False)

Title
Lady            100.000000
Ms              100.000000
Sir             100.000000
Mme             100.000000
the Countess    100.000000
Mlle            100.000000
Mrs              79.200000
Miss             69.780220
Master           57.500000
Major            50.000000
Col              50.000000
Dr               42.857143
Mr               15.667311
Capt              0.000000
Jonkheer          0.000000
Don               0.000000
Rev               0.000000
Name: Survived, dtype: float64

In [110]:
dff['is_married']=dff['Title'].apply(lambda x: 1 if x in ['Mrs','Miss'] else 0)

In [111]:
dff['is_married']

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    1
889    0
890    0
Name: is_married, Length: 891, dtype: int64

In [115]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
lr=LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)
np.mean(cross_val_score(lr,X,y,scoring='accuracy',cv=19))

np.float64(0.7021411993711163)